### ISSUE TITLE
Extension does not start

### ISSUE THREAD

**Issue by qbast** [hivemq/hivemq-prometheus-extension#5]
Prometheus extension version 4.0.1 does not work with HiveMQ 4.2.0.

Error on startup:

java.lang.NoClassDefFoundError: javax/servlet/ServletContextListener
        at org.eclipse.jetty.server.handler.ContextHandler.<clinit>(ContextHandler.java:114)
        at com.hivemq.extensions.prometheus.export.PrometheusServer.start(PrometheusServer.java:64)
        at com.hivemq.extensions.prometheus.PrometheusMainClass.extensionStart(PrometheusMainClass.java:65)
        at com.hivemq.extensions.HiveMQExtensionImpl.start(HiveMQExtensionImpl.java:133)
        at com.hivemq.extensions.HiveMQPlugins.pluginStart(HiveMQPlugins.java:209)
        at com.hivemq.extensions.loader.PluginLifecycleHandlerImpl.lambda$startPlugin$0(PluginLifecycleHandlerImpl.java:82)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: javax.servlet.ServletContextListener
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at com.hivemq.extensions.classloader.IsolatedPluginClassloader.loadClass(IsolatedPluginClassloader.java:123)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 9 common frames omitted

This is because broker itself does not provide javax.servlet.* classes and configuration in pom.xml of the extension excludes servlet-api from being included in the package.

**Comment by sbaier1** [comment]
fixed in 4.0.2
